
package com.maxart.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "PictureWebService", targetNamespace = "http://service.maxart.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface PictureWebService {


    /**
     * @param q
     * @return returns java.util.List<com.maxart.service.Picture>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findPictures", targetNamespace = "http://service.maxart.com/", className = "com.maxart.service.FindPictures")
    @ResponseWrapper(localName = "findPicturesResponse", targetNamespace = "http://service.maxart.com/", className = "com.maxart.service.FindPicturesResponse")
    @Action(input = "http://service.maxart.com/PictureWebService/findPicturesRequest", output = "http://service.maxart.com/PictureWebService/findPicturesResponse")
    public List<Picture> findPictures(
            @WebParam(name = "q", targetNamespace = "")
                    MyRequest q);

    /**
     * @return returns java.util.List<com.maxart.service.Picture>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPictures", targetNamespace = "http://service.maxart.com/", className = "com.maxart.service.GetAllPictures")
    @ResponseWrapper(localName = "getAllPicturesResponse", targetNamespace = "http://service.maxart.com/", className = "com.maxart.service.GetAllPicturesResponse")
    @Action(input = "http://service.maxart.com/PictureWebService/getAllPicturesRequest", output = "http://service.maxart.com/PictureWebService/getAllPicturesResponse")
    public List<Picture> getAllPictures();

}
